version: "3.8"
services:
    db:
        image: postgres:12.3-alpine
        container_name: db
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        expose:
            - "5432"
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
        container_name: backend
        depends_on:
            - db
        expose:
            - "8080"
#            - "9229" # remote debug inspect port
        ports:
            - "8080:8080"
#            - "9229:9229" # remote debug inspect port
        volumes:
            - ./:/usr/src/app